### ISSUE TITLE
Separate the name of the cities

### ISSUE THREAD

**Issue by ftonato** [fdaciuk/clima#1]
Auto separate the name of the cities with more than one word.

E.g.: **Porto Alegre** should be **Porto_Alegre**

``` shell
echo Porto Alegre | sed "s/ /_/g" #Porto_Alegre
echo São José dos Campos | sed "s/ /_/g" #São_José_dos_Campos
```

**Comment by caarlos0** [comment]
`| tr ' ' '_'` would work too

**Comment by fdaciuk** [comment]
You can write using quotation marks:

``` console
clima "Porto Alegre"
```

=)

**Comment by fdaciuk** [comment]
@ftonato @caarlos0 done! :dancer: :dancer: 
Thanks for your contribution :grin:
